WITH T1(MAXC, YEAR1) AS (SELECT MAX(SIZE_OF_COLONY) AS MAXC, YEAR(DIFFERENTIATION_DATE) AS YEAR1 FROM ECOLI_DATA GROUP BY YEAR1)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, ABS(SIZE_OF_COLONY - T1.MAXC) AS YEAR_DEV, ID FROM ECOLI_DATA JOIN T1 ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = T1.YEAR1
ORDER BY YEAR, YEAR_DEV ASC;